Use .editorconfig with prettier
JoshuaKGoldberg/refined-saved-replies pull request #150
Opened 2023-04-13 16:37 UTC by estevezluis

## PR Checklist

- [x] Addresses an existing open issue: fixes #51 
- [x] That issue was marked as [accepting prs](https://github.com/JoshuaKGoldberg/refined-saved-replies/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/refined-saved-replies/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Replace .prettierrc with .editorconfig for consistent styling across editors.

2023-04-13 16:58 UTC, JoshuaKGoldberg requested changes
A nice start, thanks for starting on it @estevezluis!

Always be sure to try things out locally before sending up a PR. In this case, since the code changes touch formatting, be sure to run the formatting command locally.

2023-04-13 17:36 UTC, estevezluis commented on .editorconfig
> +indent_style = tab
Is there a way to get verbose logs from the CI?

Locally, I'm not getting errors running 'yarn format --list-different'. I'll remove any caches and see if I get different results.

```
refined-saved-replies git:(ui-show-errors) ✗ yarn format --list-different
yarn run v1.22.19
$ prettier "**/*" --ignore-unknown --list-different
Done in 2.11s.
```

2023-04-13 18:08 UTC, JoshuaKGoldberg commented on .editorconfig
> +indent_style = tab
Huh, I get them locally. Did you `yarn`? Failing that, `rm -rf node_modules; yarn`?

I'm pretty sure they're from Prettier not recognizing the `.editorconfig` file by default.

2023-04-13 18:32 UTC, estevezluis commented on .editorconfig
> +indent_style = tab
I didn't noticed I removed the wildcard! Sometimes I press random keys in vim 😅

Can I add `yarn format --list-different` to pre-commit?

2023-04-13 19:10 UTC, estevezluis commented on .editorconfig
> +indent_style = tab
You are correct! Because of the wildcard typo, prettier was not recognizing .editoronfig. Thanks Joshua

2023-04-13 19:46 UTC, JoshuaKGoldberg commented on .editorconfig
> +indent_style = tab
Heh, my template package has autoformatting set up as a Git hook but I haven't copied the setup over to this one. https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/374

* https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/f1f0d5b6a2191884e6e41952a601f54d306bdc15/package.json#L29
* https://github.com/JoshuaKGoldberg/template-typescript-node-package/tree/f1f0d5b6a2191884e6e41952a601f54d306bdc15/.husky
* https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/f1f0d5b6a2191884e6e41952a601f54d306bdc15/package.json#L35

Feel free to copy that over here in a separate PR if you'd like. I'll do it manually eventually.

2023-04-13 19:47 UTC, JoshuaKGoldberg commented on .editorconfig
> +indent_style = tab
Oh, just saw you added to this one - appreciate it! But in a separate PR please 🙂

2023-04-15 23:27 UTC, estevezluis commented on .editorconfig
> +indent_style = tab
No problem! I will open a PR for this in a moment 🙂

2023-04-27 23:50 UTC, JoshuaKGoldberg commented
👋 just checking in @estevezluis, is this still something you're interested in?

2023-04-27 23:53 UTC, estevezluis commented
> 👋 just checking in @estevezluis, is this still something you're interested in?

Ah I thought I completed the task 😅 

Is there a feature I should I add to this PR?

2023-04-27 23:58 UTC, JoshuaKGoldberg commented
Ah sorry you're right, you were waiting on me! I'm surprised Prettier is working with just an `.editorconfig` and no explicit indication to use it. Cool! 

Anyway, thanks for this 😄 looks great!

2023-04-27 23:58 UTC, JoshuaKGoldberg approved these changes
🧹 🚀

2023-04-27 23:58 UTC, merged